#lang racket

(define (square x) (* x x)) 

(define (expmod b n m) 
  (cond ((= n 0) 1) 
        ((even? n)
         (remainder (* (expmod b (/ n 2) m) (expmod b (/ n 2) m)) m))
        (else 
         (remainder (* b (expmod b (- n 1) m)) m))))

(define (prime? n) 
  (define (iter times)
    (define (test) 
      (define (try a) 
        (= (expmod a n n) a))
      (try (random (- n 1))))
    (cond ((= times 0) true) 
          ((test) (iter (- times 1))) 
          (else false)))
  (iter 10))

(define (test n)
  (define (runtime) 
    (current-milliseconds))
  (define (start time)
    (define (report-true)
      (display n)
      (display " : ")
      (display (- (runtime) time))
      (newline)
      true)
    (if (prime? n)
        (report-true)
        false))
  (start (runtime)))

(define (search-for-primes from count)
  (define (iter v i)
    (cond [(> i 0)        
           (if (test v)
               (iter (+ v 1) (- i 1))
               (iter (+ v 1) i))]))
  (iter from count))

(search-for-primes 1000 1)
(search-for-primes 10000 1)
(search-for-primes 100000 1)
(search-for-primes 1000000 1)
(search-for-primes 10000000 1)
(search-for-primes 100000000 1)
(search-for-primes 1000000000 1)